# Customize directory listing/colors
alias ls='ls -hF --group-directories-first --color=auto'
alias ll='ls -lhF --color=auto'
alias l='ll'
alias la='ls -AhF --color=auto'
alias li='ls -lhF --color=yes | less -r'

# Have less repaint the screen to give me colors
alias less='less -r'

# Have grep give me colors
alias grep='grep --color'

# Alias for ack
alias ack='/usr/bin/vendor_perl/ack'
alias ack-grep='ack'

# Make directories without complaining
alias mkdir='mkdir -p'

# Make it easier to pushd
alias pd='pushd'

# Use rsync for scp in case i want to resume later
alias scpr='rsync --partial --progress --rsh=ssh'

# Show top 10 most memory intensive programs
alias mtop='ps auxf | sort -nr -k 4 | head -10'

# Instruct Bash to check if the command following sudo is also an alias
alias sudo='sudo '

# Give me vim and not vi
alias vi='vim'
