# Java
export ANT_OPTS="-Xms512M -Xmx1024M -XX:MaxPermSize=1024M"
export ANT_ARGS='-logger org.apache.tools.ant.listener.AnsiColorLogger'
export JAVA_HOME=
export JDK_HOME=$JAVA_HOME

# Debian package maintenance
export GPGKEY=5DB05144
export DEBEMAIL="Min Huang <min.huang@alumni.usc.edu>"
export DEBFULLNAME="Min Huang"

# Other
export GIT_EDITOR=vim
export SVN_EDITOR=vim
export EDITOR=vim
export WINE_PREFIX=$HOME/.wine

# Bash
export PATH=$HOME/bin:$M2_HOME/bin:$GEM_HOME/bin:$SCALA_HOME/bin:/sbin:$PATH
source $HOME/.bash_aliases
source $HOME/.bash_functions
if [ -e $HOME/.bash_local ]; then
  source $HOME/.bash_local
fi
if [ -e $HOME/.ssh/agent ]; then
  source $HOME/.ssh/agent
fi

# Colorize prompt and directories
eval $(dircolors -b $HOME/.dircolors)
promptcolors

# Show directory in urxvt title bar
case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
  ;;
    *)
  ;;
esac
