" How to use retiman's flavor of vim with plugins 'o plenty
" =========================================================
" CamelCaseMotion
"   <leader>w moves forward one word
"   <leader>b moves backwards one word
" ctrlp
"   <c-t> opens file list
"   <F5> refreshes an open file list
" vim-reporoot
"   :RepoRoot goes to the repository's root
" vim-fugitive
"   ,, opens git status
"   - stages or unstages a change
"   cc commits
"
" A note about setting mouse=a: it turns out you can't copy and paste symbols
" like ツ with mouse=a unless you hold shift while selecting with the mouse
" or hold shift when pasting (alternatively you can disable mouse=a).

" These set directives must be set first.
set nocompatible
set clipboard=unnamedplus
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8

" These set directives can be listed in any order.
set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
set colorcolumn=81
set complete=.,w,b,t,i
set completeopt=longest,menuone
set copyindent
set display+=lastline
set expandtab
set fileformat=unix
set fillchars=stl:\ ,stlnc:\ 
set formatoptions-=c
set formatoptions-=t
set gdefault
set guioptions+=c
set hidden
set history=50
set hlsearch
set incsearch
set ignorecase
set indentexpr=
set infercase
set laststatus=2
set lazyredraw
set list
set listchars=tab:│\ ,trail:·
set modelines=0
set mouse=a
set nobackup
set noerrorbells
set nofoldenable
set noswapfile
set novisualbell
set number
set pastetoggle=<F1>
set ruler
set scrolloff=15
set selection=inclusive
set shiftwidth=2
set shiftround
set showcmd
set showmode
set showmatch
set smartcase
set smartindent
set smarttab
set softtabstop=2
set t_Co=256
set t_vb=
set tabstop=2
set textwidth=0
set title
set ttyfast
set undofile
set undodir=/tmp
set wildmenu
set wildchar=<tab>
set wildignore=*.jpg,*.png,*.gif,*.swp,*.swo,*~
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*
set wildignore+=*.class,*.jar,*/target/*,*/.idea/*,*.ipr,*.iml
set wildignore+=*.o,*.obj,*.bak,*.exe
set wildignore+=*/autodoc/*
set wildmode=list:longest
set wrapmargin=0

" See vim/bundle/vim-airline/autoload/airline/extensions for vim-bufferline
" configuration.
let mapleader=','
let g:airline#extensions#bufferline#overwrite_variables=0
let g:airline#extensions#whitespace#enabled=0
let g:airline#extensions#hunks#enabled=0
let g:airline_exclude_preview=1
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_section_x='%{&ft} %{&fenc}'
let g:airline_section_y='fo=%{&fo} tw=%{&tw}'
let g:airline_section_z='%p%% %3l:%3c'
let g:bufferline_active_highlight='bufferline_selected'
let g:bufferline_active_buffer_left='['
let g:bufferline_active_buffer_right=']'
let g:bufferline_echo=0
let g:bufferline_fixed_index=0
let g:bufferline_inactive_highlight='airline_c'
let g:bufferline_rotate=1
let g:bufferline_separator=' '
let g:bufferline_show_bufnr=1
let g:csv_autocmd_arrange=1
let g:ctrlp_map='<c-0>'
let g:ctrlp_working_path_mode='rw'
let g:ctrlp_by_filename=1
let g:ctrlp_clear_cache_on_exit=0
let g:gitgutter_signs=0
let g:html_indent_inctags='html,body,head,tbody'
let g:html_indent_script1='inc'
let g:html_indent_style1='inc'
let g:neocomplcache_enable_at_startup=1
let g:neocomplcache_enable_smart_case=1
" let g:neocomplcache_enable_auto_select=1
let g:quickfix_is_open=0
let g:startify_custom_header='        Sup son? ( ¯\_(ツ)_/¯ )'
let g:startify_change_to_vcs_root=1
let g:startify_files_number=5
let g:startify_list_order=['sessions', 'files', 'bookmarks']
let g:startify_session_persistence=1
let g:SuperTabDefaultCompletionType='context'

call pathogen#infect()

syntax on
filetype plugin on
filetype indent on
colorscheme grb256
highlight bufferline_selected gui=bold cterm=bold term=bold
highlight link bufferline_selected_inactive airline_c_inactive
highlight Pmenu ctermbg=238

" Functions
function! ToggleColorColumn()
  if empty(&colorcolumn)
    setlocal colorcolumn=81
    echo 'colorcolumn=81'
  else
    setlocal colorcolumn=
    echo 'colorcolumn='
  endif
endfunction

function! ToggleMouse()
  if empty(&mouse)
    setlocal mouse=a
    echo 'mouse=a'
  else
    setlocal mouse=
    echo 'mouse='
  endif
endfunction

function! ToggleQuickFix()
  if g:quickfix_is_open
    cclose
    let g:quickfix_is_open=0
  else
    copen
    let g:quickfix_is_open=1
  endif
endfunction

" Normal, visual, and operator-pending mode mappings.
noremap <tab> %
noremap <silent> <F2> :call ToggleMouse()<cr>
noremap <silent> <F4> :call ToggleColorColumn()<cr>
noremap <silent> <F5> :call ToggleQuickFix()<cr>
noremap ; :
noremap E :Explore<cr>
noremap J <nop>
noremap K <nop>
"   Removes all trailing whitespace.
noremap <silent> T :let _s=@/<bar>:%s/\s\+$//e<bar>:let @/=_s<bar>:nohl<cr>
noremap Y y$
noremap j gj
noremap k gk

" Command mode mappings.
cnoremap w!! w !sudo tee % >/dev/null

" Normal mode mappings.
nnoremap <c-g> <c-]>
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
nnoremap <c-n> :bnext<cr>
nnoremap <c-p> :bprev<cr>
nnoremap <c-t> :RepoRoot<cr>:CtrlP<cr>
nnoremap <leader>, :Gstatus<cr>
nnoremap <leader>cc :lcd %:p:h<cr>:pwd<cr>
nnoremap <leader>d :bd<cr>:syn on<cr>
nnoremap <leader>l :set list!<cr>
nnoremap <leader>n :set number!<cr>
nnoremap <leader>p :r!xsel -b<cr>
nnoremap <leader>re :res<cr>
nnoremap <leader>rr :RepoRoot<cr>:pwd<cr>
nnoremap <leader>sd :SDelete<cr>
nnoremap <leader>ss :SSave<cr>
nnoremap <silent> <leader>t :!ctags -R * &<cr><cr>
nnoremap <leader>v :call Screen_Vars()<cr>
nnoremap <leader>q :qa!<cr>
nnoremap <leader>x vip"ry :call Send_to_Screen(@r)<cr>
nnoremap <leader>= <c-w>=<cr>
nnoremap <leader>/ :set hlsearch!<cr>

" Visual mode mappings.
vnoremap < <gv
vnoremap > >gv

" Insert mode mappings
"   See: http://vim.wikia.com/wiki/Fix_arrow_keys_that_display_A_B_C_D_on_remote_shell
"   See: http://vim.wikia.com/wiki/Restoring_indent_after_typing_hash
inoremap <expr> <esc> pumvisible() ?
    \ '<c-e>' . neocomplcache#smart_close_popup()
    \ : '<esc>'
inoremap <expr> <cr> pumvisible() ?
    \ '<c-n><c-y>'
    \ : '<cr>'
inoremap <expr> OB pumvisible() ?
    \ '<c-n>' : '<down>'
inoremap <expr> OA pumvisible() ?
    \ '<c-p>' : '<up>'
inoremap # X#

" Highlight all trailing whitespace.
autocmd BufWinEnter * let w:m2=matchadd('ErrorMsg', '\s\+$', -1)

" Project specific settings.
set secure
autocmd BufEnter,BufReadPost * silent! source ./project.vim
