alias cls='printf "\033c"'
alias df='df -h'
alias diff='colordiff'
alias du='du -c -h'
alias grep='grep --color=auto'
alias igrep='grep -i'
alias iotop='sudo iotop -oPa'
alias l='ll'
alias la='ls -AhF --color=auto'
alias less='less -r'
alias li='ls -lhF --color=yes | less -r'
alias ll='ls -lhF --color=auto'
alias loc='find -type f -print0 | wc -l --files0-from=- | tail -n1'
alias ls='ls -hF --group-directories-first --color=auto'
alias m='mplayer -fs'
alias mkdir='mkdir -p -v'
alias mtop='ps auxf | sort -nr -k 4 | head -10' # show top 10 memory intensive apps
alias pd='pushd'
alias ping='ping -c 5'
alias prename='perl-rename'
alias racket='rlwrap racket'
alias rr='repo::root'
alias scpr='rsync --partial --progress --rsh=ssh'
alias sudo='sudo ' # tell bash to respect aliases
alias tmux='tmux -2'
alias vi='vim'
