#!/usr/bin/env ruby
require "open-uri"
require "rubygems"
require "json"

USERNAME = "retiman"

query = ARGV.first.downcase

gists = JSON.parse(open("http://gist.github.com/api/v1/json/gists/#{USERNAME}").read)['gists']

gists.each do |gist|
  files = "(%s)" % gist['files'].join(', ')
  description = gist['description']
  unless description.to_s.downcase.include?(query) || files.downcase.include?(query)
    next
  end
  puts description if description
  puts files
  puts "https://gist.github.com/gists/#{gist['repo']}"
  puts
end
